# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=254)),
                ('phone_number', models.CharField(max_length=26)),
                ('area_code', models.CharField(max_length=3)),
                ('street_address', models.CharField(max_length=90)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=11)),
                ('education', models.TextField()),
                ('work_history', models.TextField()),
            ],
        ),
    ]
