# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170410_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='api.ResumeArchive'),
        ),
    ]
