# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_resume_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file_id',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='api.ResumeArchive'),
        ),
    ]
